# 网站的基本信息
site:
  tab: Eser Sevinç # Tarayıcı sekme çubuğu görüntülenir
  title: Eser Sevinç'in kişisel blogu. # Web sitesinin başlığı
  description: Yazılım sektöründe; İş Analizi, Proje Yönetimi, Ekip Yönetimi ve Liderlik gibi konular üzerine bilgi birikimi. # SEO vb. için kullanılan web sitesinin tanımı.
  language: en # 网站的语言，例如 "en" 是英文
  favicon: /favicon.ico # Tarayıcı sekmelerinde ve diğer yerlerde kullanılan web sitesinin simgesi
  theme: # Daha fazla tema için https://daisyui.com/docs/themes/
    light: light # Açık mod
    dark: dracula # Koyu mod
    code: dracula # Kod bloğunun teması https://shiki.style/themes
  date_format: ddd MMM DD YYYY # Tarih biçimi ayarı, özel biçimi destekler
  blog: # Blog ile ilgili yapılandırma
    pageSize: 8 # Sayfa başına görüntülenecek makale sayısı
  menu: #  Menü yapılandırması
    - id: home # Öğe için benzersiz tanımlayıcı
      text: Anasayfa # Menü öğesi görüntüleme
      href: / # Menü öğesi bağlantısının URL'si
      svg: "material-symbols:home-outline-rounded"
      target: _self
    - id: about
      text: Hakkımda
      href: /about
      svg: "material-symbols:info-outline-rounded"
      target: _self
    - id: blog
      text: Blog
      href: /blog
      svg: "material-symbols:book-2-outline-rounded"
      target: _self
      subItems:
        - id: all
          text: Tüm yazılar
          href: /blog
          svg: "material-symbols:ink-pen-outline-rounded"
          target: _self
        - id: tech
          text: İş ile ilgili
          href: /blog/category/work
          svg: "material-symbols:deployed-code-outline"
          target: _self
        - id: life
          text: Kişisel yaşam
          href: /blog/category/life
          svg: "material-symbols:earthquake-rounded"
          target: _self
        # Alt menü öğesi yapılandırması
    - id: project
      text: Projeler
      href: /project
      svg: "material-symbols:code-blocks-outline"
      target: _self
    - id: friend
      text: Blogroll
      href: /friend
      svg: "material-symbols:supervisor-account-outline-rounded"
      target: _self
    - id: contact
      text: İletişim
      href: /contact
      svg: "material-symbols:attach-email-outline-rounded"

# Kullanıcının Kişisel Bilgileri
user:
  name: Eser Sevinç # kullanıcı adı
  site: "https://esersevinc.com.tr" # Kullanıcının web sitesi bağlantısı
  avatar: /ES.png # Kullanıcı avatar yolu
  sidebar: # Kenar Çubuğu Yapılandırması
    social:
      - href: "https://mastodon.social/@esersevinc" # Bağlantı
        ariaLabel: Mastodon # Simgeler için erişilebilirlik etiketleri
        title: Mastodon # Simge yüzen başlık
        svg: "ri:mastodon-line"
      - href: "https://www.linkedin.com/in/esersevinc/"
        ariaLabel: Linkedin
        title: Linkedin
        svg: "ri:linkedin-line"
      - href: "https://www.strava.com/athletes/esersevinc/"
        ariaLabel: Strava
        title: Strava
        svg: "ri:riding-line"
      - href: "https://buymeacoffee.com/esersevinc"
        ariaLabel: Support my work
        title: Bir kahve ısmarla
        svg: "ri:cup-line"
  footer:
    social:
      - href: "https://buymeacoffee.com/esersevinc" # Bağlantı
        ariaLabel: Support my work # Simgeler için erişilebilirlik etiketleri
        title: Bir kahve ısmarla # Simge yüzen başlık
        svg: "ri:cup-line"
      - href: "https://github.com/Eser360"
        ariaLabel: Github
        title: Github
        svg: "ri:github-line"
      - href: "https://mastodon.social/@esersevinc"
        ariaLabel: Mastodon
        title: Mastodon
        svg: "ri:mastodon-line"
      - href: "https://www.linkedin.com/in/esersevinc/"
        ariaLabel: Linkedin
        title: Linkedin
        svg: "ri:linkedin-line"
      - href: "https://www.strava.com/athletes/esersevinc/"
        ariaLabel: Strava
        title: Strava
        svg: "si:strava"
